### ISSUE TITLE
Instalare pe amazon firestick tv

### ISSUE THREAD

**Issue by bacoscaSergiu** [moromete/plugin.video.streams#4]
buna ziua, 
pluginul se instaleaza fara eroare dar la rulare primesc urmatoarea eroare

10:04:03 T:1685885000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (1, 'Operation not permitted', '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streams-0.3.4/bin/arm/sopcast/qemu-i386')
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streams-0.3.4/default.py", line 9, in <module>
                                                from settings import SETTINGS
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streams-0.3.4/settings.py", line 6, in <module>
                                                class SETTINGS(object):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streams-0.3.4/settings.py", line 49, in SETTINGS
                                                is_exe(os.path.join(SOPCAST_ARM_PATH, QEMU))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streams-0.3.4/glob.py", line 42, in is_exe
                                                os.chmod(fpath, st.st_mode | stat.S_IEXEC)
                                            OSError: (1, 'Operation not permitted', '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streams-0.3.4/bin/arm/sopcast/qemu-i386')
                                            -->End of Python script error report<--
10:04:03 T:1499822848   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.streams/
10:04:03 T:1499822848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streams/) failed

**Comment by moromete** [comment]
Plugin-ul nu a fost facut sa ruleze pe android. Dar il poti incerca incepandu cu versiunea 0.3.6 impreuna cu plugin-ul Plexus care poate sa faca play in locul lui. in setari la engine bifeaza "use Plexus"
