### ISSUE TITLE
OSMC 2016.05-1 + streams 0.3.4 nefunctional

### ISSUE THREAD

**Issue by Alexanderis** [moromete/plugin.video.streams#7]
Nu incarca lista de canale si in loguri apare eroarea:

22:16:30 954.698669 T:1761342448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'unverified'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.streams-master/default.py", line 462, in <module>
                                                CAT_LIST(force=True)
                                              File "/home/osmc/.kodi/addons/plugin.video.streams-master/default.py", line 197, in CAT_LIST
                                                parse_ch_data()
                                              File "/home/osmc/.kodi/addons/plugin.video.streams-master/default.py", line 143, in parse_ch_data
                                                **if ((not channel['unverified']) or (SETTINGS.SHOW_UNVERIFIED=='true')):
                                            KeyError: 'unverified'**
                                            -->End of Python script error report<--

Cu versiunea 0.3.3 addon-ul este functional

**Comment by moromete** [comment]
fixed in 0.3.5
